[package]
name = "nhl_discord_bot"
version = "0.2.0"
edition = "2021"

[dependencies]
serde = "1.0.154"
serde_json = "1.0.94"
reqwest = "0.11.14"
lazy_static = "1.4.0"
futures = "0.3.26"
chrono = "0.4.23"
chrono-tz = "0.8.1"
cached = "0.42.0"
config-file = "0.2.3"

[dependencies.serenity]
default-features = false
features = [
    "builder",
    "client",
    "gateway",
    "http",
    "model",
    "utils",
    "rustls_backend",
    "unstable_discord_api",
]
version = "0.11.5"

[dependencies.tokio]
version = "1.26.0"
features = ["macros", "signal", "rt-multi-thread"]